<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>RegistroJugador_VB</RootNamespace>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
    <StartupObject>RegistroJugador_VB.Program</StartupObject>
  </PropertyGroup>
</Project>
